language: python

stages:
- install
- test
- name: deploy
  if: tag =~ tdvt

after_install:
  - curl -fL https://getcli.jfrog.io | sh

script:
  - python -m unittest

jobs:
  include:
  - python: 3.6

  - stage: deploy
    script: jfrog rt p --url=$PROD_URL --apikey=$PROD_API_KEY
