language: python

stages:
- test
- name: deploy
  if: tag =~ tdvt

script:
- python -m unittest

jobs:
  include:
  - python: 3.6
  - stage: deploy
    install:
    - npm install -g jfrog-cli-go
    script:
    - jfrog rt p --url=$PROD_URL --apikey=$PROD_API_KEY
